language: python

python:
    - 3.4

install: 
    - pip install -r requirements/test.txt

before_script:
    - python manage.py migrate

before_install:
    - pip install codecov
  
after_success:
    - codecov
  
script:
    - "coverage run --source='.' manage.py test"
